### ISSUE TITLE
Make it work

### ISSUE THREAD

**Issue by 8igMac** [8igMac/askme#2]
Create a prototype that 2 people can play.
Make it as simple as possible: 1 day work load.
Day1 building, day2 testing.

## Flow
- Create/edit your profile.
- Create/join a room.
- Matching
- Exit

## Todo
- [x] Wireframe design.
- [x] Mock it: routing and image.
- [ ] Make backend work (no UI needed) with server-sent event.
- [ ] Connect backend and frontend
- [ ] UI polish
- [x] Deploy: [Next.js deployment documentation](https://nextjs.org/docs/deployment).
- [ ] Testing with 1 people.

## Questions
- How to make the backend of the app?
  - Implement real-time chat room with websocket ([wocket.io](https://socket.io/)): is this an overkill?
  - :heavy_check_mark: Implement push notification using server-sent event?
    - [Next.js route handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)
    - [Using Server-Sent Events (SSE) to stream LLM responses in Next.js](https://upstash.com/blog/sse-streaming-llm-responses)

**Comment by 8igMac** [comment]
![Uploading wireframe.jpeg…]()
